wlc_show_commands:
# Original Show Command List
  - show run
  - show version
  - show inventory
  - show module
  - show cdp nei
  - show cdp nei det
  - show vlan
  - show span
  - show int
  - show int status
  - show int trunk
  - show int capabilities
  - show etherchannel sum
  - show swi
  - show swi detail
  - show env all
  - show powerÂ inline
  - show swi neighbors
  - show license right-to-use
  - dir
  - show ip int br
  - show ip route
  - show ip route sum
  - show ip ospf nei
  - show ip bgp sum
  - show ip arp
  - show ip dhcp snooping
  - show mac address-table
